import type { BrandInput, Industry, SemanticResult } from '../types/brand';
import { iconDescriptions } from './iconLibrary';
const lexicon: Record<Industry, string[]> = {
  Food: [
    'food',
    'snack',
    'cafe',
    'restaurant',
    'kitchen',
    'pav',
    'vada',
    'burger',
    'pizza',
    'chai',
    'coffee',
    'bakery',
    'sweet',
    'spice',
    'meal',
    'tiffin',
    'street',
  ],
  Technology: [
    'tech',
    'ai',
    'software',
    'cloud',
    'cyber',
    'data',
    'code',
    'app',
    'digital',
    'robot',
    'system',
    'nova',
    'byte',
  ],
  Finance: [
    'finance',
    'finora',
    'pay',
    'bank',
    'coin',
    'wealth',
    'capital',
    'invest',
    'money',
    'fund',
    'loan',
    'trade',
  ],
  Education: [
    'education',
    'learn',
    'academy',
    'school',
    'study',
    'book',
    'class',
    'college',
    'course',
    'pencil',
    'stationery',
    'notebook',
    'crayon',
    'ruler',
    'science',
    'stem',
    'math',
    'library',
    'online',
    'tuition',
  ],
  Travel: [
    'travel',
    'tour',
    'trip',
    'journey',
    'map',
    'mountain',
    'hotel',
    'explore',
    'darshan',
    'holiday',
  ],
  Healthcare: ['health', 'care', 'med', 'doctor', 'clinic', 'wellness', 'heart', 'life', 'yoga'],
  Beauty: ['beauty', 'salon', 'makeup', 'skin', 'glam', 'cosmetic'],
  Fashion: ['fashion', 'style', 'wear', 'clothing', 'couture', 'apparel'],
  Gaming: ['game', 'gaming', 'esports', 'play', 'arena', 'pixel', 'quest'],
  Sports: ['sports', 'sport', 'fit', 'athletic', 'run', 'fitness', 'team', 'football', 'cricket'],
  'Real Estate': ['home', 'estate', 'property', 'house', 'realty', 'space', 'interior'],
  Entertainment: ['music', 'film', 'cinema', 'entertainment', 'studio', 'media', 'sound'],
  Automobile: ['auto', 'motor', 'car', 'vehicle', 'garage', 'wheel', 'drive'],
  'E-commerce': ['shop', 'store', 'market', 'commerce', 'cart', 'buy', 'retail'],
  Legal: ['law', 'legal', 'justice', 'advocate', 'attorney', 'contract', 'court', 'rights'],
  Agriculture: ['farm', 'agri', 'organic', 'harvest', 'crop', 'leaf', 'wheat', 'soil'],
  Logistics: ['logistics', 'delivery', 'shipping', 'cargo', 'route', 'warehouse', 'supply'],
  Construction: ['build', 'builder', 'construction', 'architect', 'plan', 'roof', 'contractor'],
  Photography: ['photo', 'camera', 'lens', 'studio', 'portrait', 'wedding', 'visual'],
  Consulting: ['consult', 'advisor', 'strategy', 'growth', 'agency', 'business', 'mentor'],
  Energy: ['energy', 'solar', 'power', 'electric', 'green', 'renewable', 'eco'],
  Nonprofit: ['ngo', 'nonprofit', 'charity', 'cause', 'mission', 'community', 'foundation'],
  Hospitality: ['hotel', 'resort', 'stay', 'hospitality', 'guest', 'dining', 'lounge'],
  Manufacturing: ['factory', 'industrial', 'manufacturing', 'precision', 'supply', 'machine'],
  'Personal Brand': ['creator', 'coach', 'author', 'speaker', 'portfolio', 'personal', 'founder'],
  Other: [],
};
export const categorySymbols: Record<Industry, string[]> = {
  Food: [
    'bun',
    'cart',
    'packet',
    'pav-badge',
    'flame-plate',
    'cutlery-bun',
    'burger-badge',
    'burger-flame',
    'burger-cart',
    'burger-box',
    'burger-cutlery',
    'burger-spark',
  ],
  Technology: [
    'circuit',
    'nodes',
    'cube',
    'orbit',
    'cloud',
    'chip',
    'ai-chip',
    'cloud-chip',
    'data-nodes',
    'robot-circuit',
    'cyber-shield',
    'app-cube',
    'code-orbit',
    'server-cloud',
    'nova-spark',
  ],
  Finance: [
    'coin',
    'graph',
    'shield',
    'arrow',
    'rupee',
    'bars',
    'pay-shield',
    'wealth-graph',
    'bank-column',
    'rupee-growth',
    'trade-bars',
    'loan-key',
    'capital-badge',
  ],
  Education: [
    'pencil',
    'stationery',
    'pencil-bundle',
    'notebook',
    'notebook-pencil',
    'crayons',
    'crayon-badge',
    'ruler',
    'ruler-pencil',
    'backpack',
    'backpack-school',
    'clipboard',
    'clipboard-course',
    'artbrushes',
    'art-class',
    'paperclip',
    'paper-pencil',
    'schoolhouse',
    'schoolhouse-book',
    'laptop',
    'online-class',
    'globe',
    'global-learning',
    'calculator',
    'math-academy',
    'microscope',
    'science-school',
    'atom',
    'rocket',
    'stem-rocket',
    'library',
    'library-badge',
    'book',
    'lamp',
    'cap',
    'pages',
    'knowledge',
    'academy-cap',
    'book-lamp',
    'course-pages',
    'study-spark',
    'school-shield',
    'class-pencil',
    'learn-orbit',
  ],
  Travel: [
    'pin',
    'compass',
    'mountain',
    'sun-road',
    'suitcase',
    'road',
    'map-suitcase',
    'mountain-compass',
    'hotel-key',
    'trip-road',
    'darshan-sun',
  ],
  Healthcare: [
    'heart',
    'pulse',
    'cross',
    'leaf',
    'care-shield',
    'care-circle',
    'clinic-leaf',
    'wellness-heart',
    'doctor-shield',
    'yoga-leaf',
    'life-pulse',
    'medical-circle',
  ],
  Beauty: [
    'sparkle',
    'flower',
    'face',
    'crown',
    'curve',
    'leaf',
    'skin-flower',
    'salon-face',
    'glam-crown',
    'cosmetic-leaf',
    'makeup-curve',
  ],
  Fashion: [
    'hanger',
    'crown',
    'flower',
    'curve',
    'sparkle',
    'thread',
    'style-hanger',
    'couture-crown',
    'apparel-thread',
    'wear-leaf',
  ],
  Gaming: [
    'controller',
    'lightning',
    'game-shield',
    'pixels',
    'trophy',
    'joystick',
    'game-pixels',
    'arena-trophy',
    'esports-shield',
    'quest-orbit',
    'play-bolt',
  ],
  Sports: [
    'trophy',
    'ball',
    'lightning',
    'medal',
    'shoe',
    'flag',
    'cricket-medal',
    'fitness-shoe',
    'team-flag',
    'athletic-bolt',
  ],
  'Real Estate': [
    'house',
    'roof',
    'window',
    'building',
    'key',
    'floor',
    'home-key',
    'interior-window',
    'realty-roof',
    'property-building',
    'space-floor',
  ],
  Entertainment: [
    'music',
    'play-button',
    'film',
    'headphones',
    'microphone',
    'spotlight',
    'sound-wave',
    'studio-film',
    'media-play',
    'podcast-mic',
    'cinema-star',
  ],
  Automobile: [
    'wheel',
    'car',
    'gear',
    'road',
    'speed',
    'key',
    'garage-gear',
    'drive-speed',
    'auto-key',
    'motor-bolt',
  ],
  'E-commerce': [
    'bag',
    'cart-shop',
    'package',
    'store',
    'tag',
    'basket',
    'shop-bag',
    'market-store',
    'commerce-cart',
    'retail-spark',
    'delivery-cube',
  ],
  Legal: [
    'legal-shield',
    'law-pages',
    'justice-badge',
    'contract-pen',
    'shield',
    'book',
    'knowledge',
    'pencil',
    'building',
    'capital-badge',
  ],
  Agriculture: [
    'agri-leaf',
    'farm-sun',
    'organic-badge',
    'harvest-wheat',
    'leaf',
    'wheat',
    'basket',
    'sun-road',
    'eco-shield',
    'green-energy',
  ],
  Logistics: [
    'logistics-box',
    'delivery-speed',
    'route-pin',
    'warehouse-store',
    'package',
    'road',
    'speed',
    'pin',
    'delivery-cube',
    'supply-chain',
  ],
  Construction: [
    'builder-gear',
    'construction-roof',
    'plan-building',
    'property-hammer',
    'building',
    'floor',
    'roof',
    'gear',
    'house',
    'property-building',
  ],
  Photography: [
    'camera-frame',
    'photo-lens',
    'studio-camera',
    'portrait-mark',
    'film',
    'spotlight',
    'sparkle',
    'face',
    'media-play',
    'studio-film',
  ],
  Consulting: [
    'consulting-nodes',
    'strategy-graph',
    'advisor-shield',
    'growth-orbit',
    'nodes',
    'graph',
    'compass',
    'lamp',
    'venture-nodes',
    'wealth-graph',
  ],
  Energy: [
    'green-energy',
    'solar-road',
    'power-bolt',
    'eco-shield',
    'lightning',
    'leaf',
    'sun-road',
    'orbit',
    'care-shield',
    'sparkle',
  ],
  Nonprofit: [
    'cause-heart',
    'community-circle',
    'charity-hand',
    'mission-badge',
    'heart',
    'care-circle',
    'leaf',
    'shield',
    'nodes',
    'sparkle',
  ],
  Hospitality: [
    'hotel-pin',
    'resort-sun',
    'stay-key',
    'dining-stay',
    'suitcase',
    'pin',
    'key',
    'cup',
    'house',
    'store',
  ],
  Manufacturing: [
    'factory-gear',
    'industrial-cube',
    'precision-chip',
    'supply-chain',
    'gear',
    'cube',
    'chip',
    'building',
    'package',
    'nodes',
  ],
  'Personal Brand': [
    'creator-monogram',
    'speaker-mark',
    'author-book',
    'coach-compass',
    'monogram',
    'face',
    'microphone',
    'book',
    'compass',
    'founder-mark',
  ],
  Other: [
    'orbit',
    'facets',
    'monogram',
    'nodes',
    'sparkle',
    'cube',
    'abstract-orbit',
    'founder-mark',
    'venture-nodes',
    'studio-facets',
  ],
};
export const iconSearchTags: Record<string, string[]> = {
  bun: ['burger', 'vada', 'pav', 'snack', 'food', 'bun'],
  cart: ['street', 'cart', 'stall', 'food truck', 'vendor'],
  packet: ['takeaway', 'delivery', 'packet', 'snack box'],
  'pav-badge': ['badge', 'seal', 'street food', 'pav'],
  'flame-plate': ['spicy', 'hot', 'flame', 'grill'],
  'cutlery-bun': ['restaurant', 'dining', 'cutlery', 'meal'],
  'burger-badge': ['burger', 'badge', 'seal'],
  'burger-flame': ['burger', 'spicy', 'grill', 'flame'],
  'burger-cart': ['burger', 'street', 'cart'],
  'burger-box': ['burger', 'takeaway', 'delivery'],
  'burger-cutlery': ['burger', 'restaurant', 'dining'],
  'burger-spark': ['burger', 'fresh', 'premium'],
  cup: ['coffee', 'cafe', 'tea', 'chai', 'drink'],
  'coffee-bean': ['coffee', 'bean', 'roast'],
  kettle: ['tea', 'chai', 'kettle'],
  'cup-badge': ['coffee', 'cafe', 'badge', 'seal'],
  steam: ['coffee', 'chai', 'hot', 'steam'],
  'cup-cart': ['coffee', 'cart', 'cafe', 'street'],
  'coffee-leaf': ['coffee', 'organic', 'leaf'],
  'coffee-store': ['coffee', 'shop', 'cafe', 'store'],
  'coffee-spark': ['coffee', 'premium', 'fresh'],
  'tea-badge': ['tea', 'chai', 'badge'],
  pizza: ['pizza', 'slice', 'food'],
  'pizza-box': ['pizza', 'takeaway', 'box', 'delivery'],
  'pizza-badge': ['pizza', 'badge', 'seal'],
  oven: ['pizza', 'oven', 'baked'],
  'flame-pizza': ['pizza', 'flame', 'wood fired'],
  'pizza-plate': ['pizza', 'restaurant', 'plate'],
  'pizza-cart': ['pizza', 'cart', 'street'],
  'pizza-flame-badge': ['pizza', 'flame', 'badge'],
  'pizza-spark': ['pizza', 'fresh', 'premium'],
  bread: ['bread', 'bakery', 'loaf'],
  cake: ['cake', 'sweet', 'dessert', 'bakery'],
  wheat: ['wheat', 'grain', 'bakery', 'organic'],
  'bread-badge': ['bread', 'badge', 'seal', 'bakery'],
  'bakery-shop': ['bakery', 'shop', 'store'],
  'rolling-pin': ['bakery', 'baker', 'rolling pin'],
  'bread-wheat': ['bread', 'wheat', 'artisan'],
  'cake-spark': ['cake', 'sweet', 'premium'],
  'sweet-box': ['sweet', 'dessert', 'takeaway'],
  book: ['book', 'education', 'school', 'reading'],
  globe: ['globe', 'global', 'world', 'online', 'international', 'education'],
  laptop: ['laptop', 'online', 'edtech', 'class', 'course', 'digital learning'],
  calculator: ['calculator', 'math', 'tuition', 'numbers', 'school'],
  microscope: ['microscope', 'science', 'lab', 'biology', 'school'],
  atom: ['atom', 'science', 'stem', 'physics', 'learning'],
  rocket: ['rocket', 'launch', 'stem', 'kids', 'academy'],
  schoolhouse: ['school', 'schoolhouse', 'building', 'kids', 'academy'],
  library: ['library', 'books', 'reading', 'school', 'study'],
  stationery: ['pencil', 'stationery', 'pens', 'ruler', 'school supplies'],
  notebook: ['notebook', 'notes', 'paper', 'pencil', 'class'],
  crayons: ['crayon', 'crayons', 'markers', 'kids', 'art class'],
  ruler: ['ruler', 'pencil', 'geometry', 'school supplies'],
  backpack: ['backpack', 'school bag', 'kids', 'student'],
  clipboard: ['clipboard', 'checklist', 'exam', 'course'],
  artbrushes: ['paint', 'brushes', 'art', 'creative class', 'pencil'],
  paperclip: ['paperclip', 'paper', 'notes', 'pencil', 'document'],
  lamp: ['study', 'idea', 'knowledge', 'learning'],
  pencil: ['pencil', 'writing', 'class', 'school'],
  cap: ['graduation', 'college', 'academy', 'university'],
  pages: ['pages', 'course', 'book', 'study'],
  knowledge: ['knowledge', 'badge', 'book', 'learning'],
  'academy-cap': ['academy', 'graduation', 'cap', 'college', 'university'],
  'book-lamp': ['book', 'study', 'knowledge', 'coaching'],
  'course-pages': ['course', 'online course', 'pages', 'lesson'],
  'online-class': ['online', 'online class', 'laptop', 'course', 'edtech'],
  'global-learning': ['global', 'globe', 'online learning', 'international'],
  'math-academy': ['math', 'calculator', 'academy', 'tuition'],
  'science-school': ['science', 'microscope', 'lab', 'stem'],
  'stem-rocket': ['stem', 'rocket', 'science', 'kids'],
  'library-badge': ['library', 'reading', 'book', 'badge'],
  'schoolhouse-book': ['school', 'schoolhouse', 'academy', 'book'],
  'pencil-bundle': ['pencil', 'stationery', 'bundle', 'school supplies'],
  'notebook-pencil': ['notebook', 'pencil', 'notes', 'class'],
  'crayon-badge': ['crayon', 'kids', 'art', 'badge'],
  'ruler-pencil': ['ruler', 'pencil', 'geometry', 'stationery'],
  'backpack-school': ['backpack', 'school bag', 'student', 'kids'],
  'clipboard-course': ['clipboard', 'course', 'exam', 'checklist'],
  'art-class': ['art', 'brushes', 'creative', 'class'],
  'paper-pencil': ['paper', 'paperclip', 'pencil', 'notes'],
  'study-spark': ['study', 'tutor', 'coaching', 'bright'],
  'school-shield': ['school', 'shield', 'trust', 'kids'],
  'class-pencil': ['class', 'classroom', 'pencil', 'school'],
  'learn-orbit': ['learn', 'online learning', 'edtech', 'course'],
  circuit: ['tech', 'circuit', 'software'],
  nodes: ['network', 'data', 'connected', 'ai'],
  cube: ['3d', 'product', 'software', 'app'],
  orbit: ['ai', 'innovation', 'research', 'space'],
  cloud: ['cloud', 'saas', 'server'],
  chip: ['chip', 'hardware', 'ai'],
  'ai-chip': ['ai', 'chip', 'machine learning'],
  'cloud-chip': ['cloud', 'ai', 'infrastructure'],
  'data-nodes': ['data', 'analytics', 'network'],
  'robot-circuit': ['robot', 'automation', 'ai'],
  'cyber-shield': ['cyber', 'security', 'shield'],
  'app-cube': ['app', 'software', 'product'],
  'code-orbit': ['code', 'developer', 'software'],
  'server-cloud': ['server', 'cloud', 'hosting'],
  'nova-spark': ['nova', 'startup', 'innovation'],
  coin: ['coin', 'money', 'finance'],
  graph: ['growth', 'graph', 'investment'],
  shield: ['trust', 'shield', 'safe'],
  arrow: ['growth', 'up', 'arrow'],
  rupee: ['rupee', 'india', 'payment'],
  bars: ['bars', 'analytics', 'growth'],
  'pay-shield': ['payment', 'pay', 'secure'],
  'wealth-graph': ['wealth', 'investment', 'growth'],
  'bank-column': ['bank', 'finance', 'institution'],
  'rupee-growth': ['rupee', 'growth', 'finance'],
  'trade-bars': ['trade', 'market', 'bars'],
  'loan-key': ['loan', 'key', 'finance'],
  'capital-badge': ['capital', 'trust', 'badge'],
  'legal-shield': ['law', 'legal', 'shield', 'attorney', 'advocate'],
  'law-pages': ['law', 'legal', 'contract', 'court', 'document'],
  'justice-badge': ['justice', 'rights', 'legal', 'badge'],
  'contract-pen': ['contract', 'agreement', 'pen', 'legal'],
  'agri-leaf': ['agriculture', 'agri', 'farm', 'leaf', 'organic'],
  'farm-sun': ['farm', 'sun', 'soil', 'crop'],
  'organic-badge': ['organic', 'natural', 'leaf', 'badge'],
  'harvest-wheat': ['harvest', 'wheat', 'crop', 'basket'],
  'logistics-box': ['logistics', 'shipping', 'cargo', 'box'],
  'delivery-speed': ['delivery', 'fast', 'courier', 'speed'],
  'route-pin': ['route', 'map', 'pin', 'tracking'],
  'warehouse-store': ['warehouse', 'storage', 'store', 'shipping'],
  'builder-gear': ['builder', 'construction', 'gear', 'contractor'],
  'construction-roof': ['construction', 'roof', 'house', 'contractor'],
  'plan-building': ['plan', 'architecture', 'floor', 'building'],
  'property-hammer': ['construction', 'build', 'power', 'property'],
  'camera-frame': ['photo', 'camera', 'frame', 'photography'],
  'photo-lens': ['photo', 'lens', 'camera', 'visual'],
  'studio-camera': ['studio', 'camera', 'film', 'shoot'],
  'portrait-mark': ['portrait', 'face', 'photography'],
  'consulting-nodes': ['consulting', 'advisor', 'network', 'business'],
  'strategy-graph': ['strategy', 'growth', 'graph', 'business'],
  'advisor-shield': ['advisor', 'trust', 'consulting', 'strategy'],
  'growth-orbit': ['growth', 'strategy', 'startup', 'scale'],
  'green-energy': ['green', 'energy', 'electric', 'renewable'],
  'solar-road': ['solar', 'sun', 'power', 'energy'],
  'power-bolt': ['power', 'electric', 'energy', 'bolt'],
  'eco-shield': ['eco', 'green', 'safe', 'renewable'],
  'cause-heart': ['cause', 'charity', 'heart', 'nonprofit'],
  'community-circle': ['community', 'ngo', 'people', 'circle'],
  'charity-hand': ['charity', 'care', 'help', 'foundation'],
  'mission-badge': ['mission', 'foundation', 'badge', 'trust'],
  'hotel-pin': ['hotel', 'travel', 'stay', 'pin'],
  'resort-sun': ['resort', 'sun', 'holiday', 'stay'],
  'stay-key': ['stay', 'hotel', 'key', 'guest'],
  'dining-stay': ['dining', 'guest', 'hospitality', 'lounge'],
  'factory-gear': ['factory', 'industrial', 'machine', 'gear'],
  'industrial-cube': ['industrial', 'manufacturing', 'cube', 'product'],
  'precision-chip': ['precision', 'machine', 'chip', 'engineering'],
  'supply-chain': ['supply', 'chain', 'manufacturing', 'logistics'],
  'creator-monogram': ['creator', 'personal', 'portfolio', 'monogram'],
  'speaker-mark': ['speaker', 'podcast', 'voice', 'personal'],
  'author-book': ['author', 'writer', 'book', 'personal'],
  'coach-compass': ['coach', 'mentor', 'fitness', 'direction'],
};
const normalize = (s: string) =>
  s
    .replace(/([a-z])([A-Z])/g, '$1 $2')
    .toLowerCase()
    .normalize('NFKD')
    .replace(/[^\p{L}\p{N}]+/gu, ' ')
    .trim();
function matches(s: string, k: string) {
  const words = normalize(s).split(' ');
  return (
    words.some((w) => {
      if (w === k) return true;
      if (k.length < 4 || !w.includes(k)) return false;
      const remainder = w.replace(k, '');
      return remainder.length >= 3 || ['s', 'es', 'ly', 'io'].includes(remainder);
    }) ||
    (k === 'pav' && normalize(s).includes('vadapav'))
  );
}
const rankSymbols = (symbols: string[], text: string) =>
  [...symbols].sort((a, b) => scoreSymbol(b, text) - scoreSymbol(a, text));
function scoreSymbol(symbol: string, text: string) {
  const keyTokens = normalize(symbol.replace(/-/g, ' ')).split(' '),
    descriptionTokens = normalize(iconDescriptions[symbol] || '').split(' '),
    tags = iconSearchTags[symbol] || [];
  return (
    keyTokens.reduce(
      (score, token) => score + (token.length > 2 && matches(text, token) ? 4 : 0),
      0,
    ) +
    descriptionTokens.reduce(
      (score, token) => score + (token.length > 2 && matches(text, token) ? 1 : 0),
      0,
    ) +
    tags.reduce((score, tag) => {
      const normalizedTag = normalize(tag);
      return (
        score + (matches(text, normalizedTag) || normalize(text).includes(normalizedTag) ? 6 : 0)
      );
    }, 0)
  );
}
export function analyzeBrand(brand: BrandInput): SemanticResult {
  const scores = (Object.entries(lexicon) as [Industry, string[]][])
    .map(([category, words]) => ({
      category,
      score:
        words.reduce(
          (v, k) =>
            v +
            (matches(brand.brandName, k) ? 10 : 0) +
            (matches(brand.tagline, k) ? 3 : 0) +
            (matches(brand.description, k) ? 2 : 0),
          0,
        ) + (brand.industry === category ? 5 : 0),
      keywords: words.filter((k) =>
        matches(brand.brandName + ' ' + brand.tagline + ' ' + brand.description, k),
      ),
    }))
    .sort((a, b) => b.score - a.score);
  const best = scores[0],
    category = best.score ? best.category : 'Other';
  let symbols = [...categorySymbols[category]];
  let theme: string = category;
  const foodText = brand.brandName + ' ' + brand.tagline + ' ' + brand.description;
  if (category === 'Food' && !/vada|pav|burger/i.test(brand.brandName)) {
    if (/coffee|chai|cafe|tea\b/i.test(foodText)) {
      symbols = [
        'cup',
        'coffee-bean',
        'kettle',
        'cup-badge',
        'steam',
        'cup-cart',
        'coffee-leaf',
        'coffee-store',
        'tea-badge',
        'coffee-spark',
        'store',
        'leaf',
      ];
      theme = 'Café & beverages';
    } else if (/pizza/i.test(foodText)) {
      symbols = [
        'pizza',
        'pizza-box',
        'pizza-badge',
        'oven',
        'flame-pizza',
        'pizza-plate',
        'pizza-cart',
        'pizza-flame-badge',
        'pizza-spark',
        'cart',
        'store',
        'flame-plate',
      ];
      theme = 'Pizza kitchen';
    } else if (/bakery|bread|cake|sweet/i.test(foodText)) {
      symbols = [
        'bread',
        'cake',
        'wheat',
        'bread-badge',
        'bakery-shop',
        'rolling-pin',
        'bread-wheat',
        'cake-spark',
        'sweet-box',
        'store',
        'sparkle',
      ];
      theme = 'Bakery';
    }
  }
  symbols = rankSymbols(symbols, foodText);
  const source = best.keywords.some((k) => matches(brand.brandName, k))
    ? 'Brand name'
    : best.keywords.length
      ? 'Name + brand context'
      : category === 'Other'
        ? 'Geometric fallback'
        : 'Selected industry';
  return {
    category,
    keywords: best.keywords,
    symbols,
    theme,
    source,
    rationale:
      category === 'Other'
        ? `No dictionary category matches “${brand.brandName}”. The fallback uses its initial and geometric forms to make a distinct identity without inventing a literal meaning.`
        : `${source} connects “${brand.brandName}” to ${theme.toLowerCase()}. ${brand.personality.join(', ') || 'Balanced'} personality guides weights and spacing; ${brand.logoStyle.toLowerCase()} guides the composition.`,
  };
}
