export const topics = {
  biology: [
    {
      id: "photosynthesis",
      title: "Photosynthesis",
      icon: "🌱",
      description: "See how plants convert sunlight into energy.",
      visualization: "photosynthesis",
    },
    {
      id: "human-heart",
      title: "Human Heart",
      icon: "❤️",
      description: "Follow the flow of blood through the heart.",
      visualization: "human-heart",
    },
    {
      id: "cell",
      title: "Cell Structure",
      icon: "🔬",
      description: "Explore the organelles inside a cell.",
      visualization: "cell",
    },
    {
      id: "digestion",
      title: "Digestive System",
      icon: "🫃",
      description: "Follow food through the digestive system.",
      visualization: "digestion",
    },
    {
      id: "dna",
      title: "DNA Replication",
      icon: "🧬",
      description: "Watch DNA unzip and replicate.",
      visualization: "dna",
    },
  ],

  physics: [
    {
      id: "newton",
      title: "Newton's Laws",
      icon: "🚗",
      description: "Experiment with force, mass and acceleration.",
      visualization: "newton",
    },
    {
      id: "projectile",
      title: "Projectile Motion",
      icon: "🏀",
      description: "See how angle and velocity affect motion.",
      visualization: "projectile",
    },
    {
      id: "electricity",
      title: "Electric Circuit",
      icon: "⚡",
      description: "Watch current flow through a circuit.",
      visualization: "electricity",
    },
    {
      id: "solar-system",
      title: "Solar System",
      icon: "🪐",
      description: "Explore planetary orbits.",
      visualization: "solar-system",
    },
    {
      id: "waves",
      title: "Wave Motion",
      icon: "〰️",
      description: "Experiment with amplitude and frequency.",
      visualization: "waves",
    },
  ],

  chemistry: [
    {
      id: "atom",
      title: "Atomic Structure",
      icon: "⚛️",
      description: "Explore protons, neutrons and electrons.",
      visualization: "atom",
    },
    {
      id: "bonding",
      title: "Chemical Bonding",
      icon: "🔗",
      description: "See how atoms form bonds.",
      visualization: "bonding",
    },
    {
      id: "acid-base",
      title: "Acids & Bases",
      icon: "🧪",
      description: "Explore pH and acid-base reactions.",
      visualization: "acid-base",
    },
    {
      id: "reaction",
      title: "Chemical Reaction",
      icon: "💥",
      description: "Watch reactants transform into products.",
      visualization: "reaction",
    },
    {
      id: "states",
      title: "States of Matter",
      icon: "🧊",
      description: "See how particles behave in different states.",
      visualization: "states",
    },
  ],

  geography: [
    {
      id: "water-cycle",
      title: "Water Cycle",
      icon: "💧",
      description: "Follow water through evaporation and rainfall.",
      visualization: "water-cycle",
    },
    {
      id: "rock-cycle",
      title: "Rock Cycle",
      icon: "🪨",
      description: "Explore how rocks transform.",
      visualization: "rock-cycle",
    },
    {
      id: "volcano",
      title: "Volcano",
      icon: "🌋",
      description: "See what happens during a volcanic eruption.",
      visualization: "volcano",
    },
    {
      id: "earth-layers",
      title: "Earth's Layers",
      icon: "🌍",
      description: "Explore the structure of Earth.",
      visualization: "earth-layers",
    },
    {
      id: "tectonics",
      title: "Plate Tectonics",
      icon: "🌎",
      description: "Watch tectonic plates move.",
      visualization: "tectonics",
    },
  ],

  computerScience: [
    {
      id: "binary-search",
      title: "Binary Search",
      icon: "🔎",
      description: "Watch the search space get divided.",
      visualization: "binary-search",
    },
    {
      id: "sorting",
      title: "Sorting Algorithms",
      icon: "📊",
      description: "Visualize elements being sorted.",
      visualization: "sorting",
    },
    {
      id: "stack-queue",
      title: "Stack & Queue",
      icon: "📚",
      description: "Understand push, pop and queue operations.",
      visualization: "stack-queue",
    },
    {
      id: "cpu-memory",
      title: "CPU & Memory",
      icon: "🖥️",
      description: "Follow instructions between CPU and memory.",
      visualization: "cpu-memory",
    },
    {
      id: "network",
      title: "Computer Networks",
      icon: "🌐",
      description: "Watch packets travel between computers.",
      visualization: "network",
    },
  ],
};